Repository TopAcademy2022/topchat-logic, pull requests merged in 2025-02, with the labels that each got.

#41 Added tests for GroupService. Closed #25
  Tests/TopChat.Tests/TopChat.Tests/GroupServiceTests.cs
Labels: testing

#38 Added tests for DependencyInjectionSetup. Closed #36
  Tests/TopChat.Tests/TopChat.Tests/DependencyInjectionSetupTests.cs
  Tests/TopChat.Tests/TopChat.Tests/TopChatTests.cs
  TopChat/Infrastructure/DependencyInjectionSetup.cs
  TopChat/Services/Interfaces/ADatabaseConnection.cs
Labels: testing

#46 Fixed project type. Closed #43
  TopChat/Models/Group.cs
  TopChat/Models/Message.cs
  TopChat/Services/ConnectionProviderUdp.cs
  TopChat/Services/DataConverterService.cs
  TopChat/Services/GroupService.cs
  TopChat/Services/MongoDBConnection.cs
  TopChat/Services/UserServes.cs
  TopChat/TopChat.csproj
Labels: bug

#47 Added receive bytes. Closed #39
  Tests/TopChat.Tests/TopChat.Tests/TopChatTests.cs
  TopChat/Services/ConnectionProviderUdp.cs
  TopChat/Services/Interfaces/IConnectionProvider.cs
  TopChat/Services/Interfaces/IUserServes.cs
  TopChat/Services/UserServes.cs
Labels: enhancement, testing

#51 Added plugin registration. Closed #50
  TopChat.API/Interfaces/IConnectionProvider.cs
  TopChat.API/Interfaces/IDependencyInjection.cs
  TopChat.API/Interfaces/IPlugin.cs
  TopChat.API/Interfaces/IUserInterface.cs
  TopChat.Application/Services/KernelService.cs
  TopChat.Domain/Interfaces/IKernelService.cs
  TopChat.Infrastruction/Services/DefaultDependencyInjection.cs
  TopChat.UI/App.cs
  TopChat.UI/Program.cs
  TopChat.UI/UtilitiUserInterface.cs
  TopChat.UI/UtilityUserInterface.cs
Labels: enhancement
