Repository TopAcademy2022/topchat-logic, pull requests merged in 2025-01, with the labels that each got.

#2 Added project files. Closed #1
  TopChat.sln
  TopChat/Models/Message.cs
  TopChat/Models/NetworkData.cs
  TopChat/Models/User.cs
  TopChat/Services/ConnectionProviderUdp.cs
  TopChat/Services/DataConverterService.cs
  TopChat/Services/Interfaces/IConnectionProvider.cs
  TopChat/Services/Interfaces/IDataConverterService.cs
  TopChat/Services/Interfaces/INetworkDataService.cs
  TopChat/Services/NetworkDataService.cs
  TopChat/TopChat.csproj
Labels: enhancement

#18 Added Github action. Closed #15
  .github/workflows/dotnet.yml
Labels: testing

#14 Added unit testing. Closed #3
  Tests/TopChat.Tests/TopChat.Tests.sln
  Tests/TopChat.Tests/TopChat.Tests/TopChat.Tests.csproj
  Tests/TopChat.Tests/TopChat.Tests/TopChatTests.cs
  TopChat.sln
  TopChat/TopChat.csproj
Labels: enhancement, testing

#21 Added custom files to messages. Closed #8
  TopChat/Models/Media.cs
  TopChat/Models/Message.cs
Labels: enhancement

#16 Added group chat. Closed #7
  TopChat/Models/Group.cs
  TopChat/Services/GroupService.cs
  TopChat/Services/Interfaces/IGroupService.cs
Labels: enhancement

#28 Added tests for MessageServiceClient. Closed #26
  Tests/TopChat.Tests/TopChat.Tests/MessageServiceClientTests.cs
  Tests/TopChat.Tests/TopChat.Tests/TopChat.Tests.csproj
  Tests/TopChat.Tests/TopChat.Tests/TopChatTests.cs
  TopChat/Models/Media.cs
  TopChat/Services/DataConverterService.cs
  TopChat/Services/Interfaces/IMessageService.cs
  TopChat/Services/MessageServiceClient.cs
  TopChat/Services/NetworkDataService.cs
  TopChat/TopChat.csproj
Labels: enhancement, testing

#32 Added Database working. Closed #6
  Tests/TopChat.Tests/TopChat.Tests/TopChat.Tests.csproj
  Tests/TopChat.Tests/TopChat.Tests/TopChatTests.cs
  TopChat/Services/Interfaces/ADatabaseConnection.cs
  TopChat/Services/MongoDBConnection.cs
  TopChat/Services/SqliteConnection.cs
  TopChat/TopChat.csproj
Labels: enhancement, testing

#27 Added tests for ConnectionProviderUdp. Closed #24
  Tests/TopChat.Tests/TopChat.Tests/TopChatTests.cs
  TopChat/Services/ConnectionProviderUdp.cs
  TopChat/TopChat.csproj
Labels: testing

#33 Added UserService class. Closed #4
  TopChat/Services/Interfaces/IUserServes.cs
  TopChat/Services/UserServes.cs
Labels: enhancement

#35 Added dependency injection. Closed #10
  TopChat/Infrastructure/DependencyInjectionSetup.cs
  TopChat/TopChat.csproj
Labels: enhancement
